version: '3'
services:
  nodeapp:
    build:
      context: .
      target: dev
    networks:
      - devops-test
    depends_on:
      - graphite-web
    container_name: nodejs-app 

  graphite-web:
    image: graphiteapp/graphite-statsd
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    networks:
      - devops-test
    container_name: graphite

networks:
  devops-test:
    driver: bridge

